#ifndef ALLOVERSE_READER_H
#define ALLOVERSE_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef struct Alloverse_Mat4 Alloverse_Mat4_t;
typedef const Alloverse_Mat4_t *Alloverse_Mat4_struct_t;
typedef Alloverse_Mat4_t *Alloverse_Mat4_mutable_struct_t;
typedef const Alloverse_Mat4_t *Alloverse_Mat4_vec_t;
typedef Alloverse_Mat4_t *Alloverse_Mat4_mutable_vec_t;
typedef struct Alloverse_Vec3 Alloverse_Vec3_t;
typedef const Alloverse_Vec3_t *Alloverse_Vec3_struct_t;
typedef Alloverse_Vec3_t *Alloverse_Vec3_mutable_struct_t;
typedef const Alloverse_Vec3_t *Alloverse_Vec3_vec_t;
typedef Alloverse_Vec3_t *Alloverse_Vec3_mutable_vec_t;

typedef const struct Alloverse_State_table *Alloverse_State_table_t;
typedef struct Alloverse_State_table *Alloverse_State_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_State_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_State_mutable_vec_t;
typedef const struct Alloverse_Entity_table *Alloverse_Entity_table_t;
typedef struct Alloverse_Entity_table *Alloverse_Entity_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_Entity_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_Entity_mutable_vec_t;
typedef const struct Alloverse_Components_table *Alloverse_Components_table_t;
typedef struct Alloverse_Components_table *Alloverse_Components_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_Components_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_Components_mutable_vec_t;
typedef const struct Alloverse_TransformComponent_table *Alloverse_TransformComponent_table_t;
typedef struct Alloverse_TransformComponent_table *Alloverse_TransformComponent_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_TransformComponent_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_TransformComponent_mutable_vec_t;
typedef const struct Alloverse_RelationshipsComponent_table *Alloverse_RelationshipsComponent_table_t;
typedef struct Alloverse_RelationshipsComponent_table *Alloverse_RelationshipsComponent_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_RelationshipsComponent_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_RelationshipsComponent_mutable_vec_t;
typedef const struct Alloverse_LiveMediaMetadata_table *Alloverse_LiveMediaMetadata_table_t;
typedef struct Alloverse_LiveMediaMetadata_table *Alloverse_LiveMediaMetadata_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_LiveMediaMetadata_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_LiveMediaMetadata_mutable_vec_t;
typedef const struct Alloverse_LiveMediaComponent_table *Alloverse_LiveMediaComponent_table_t;
typedef struct Alloverse_LiveMediaComponent_table *Alloverse_LiveMediaComponent_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_LiveMediaComponent_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_LiveMediaComponent_mutable_vec_t;
typedef const struct Alloverse_ClockComponent_table *Alloverse_ClockComponent_table_t;
typedef struct Alloverse_ClockComponent_table *Alloverse_ClockComponent_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_ClockComponent_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_ClockComponent_mutable_vec_t;
typedef const struct Alloverse_IntentComponent_table *Alloverse_IntentComponent_table_t;
typedef struct Alloverse_IntentComponent_table *Alloverse_IntentComponent_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_IntentComponent_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_IntentComponent_mutable_vec_t;
typedef const struct Alloverse_NumberAnimationValue_table *Alloverse_NumberAnimationValue_table_t;
typedef struct Alloverse_NumberAnimationValue_table *Alloverse_NumberAnimationValue_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_NumberAnimationValue_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_NumberAnimationValue_mutable_vec_t;
typedef const struct Alloverse_VectorAnimationValue_table *Alloverse_VectorAnimationValue_table_t;
typedef struct Alloverse_VectorAnimationValue_table *Alloverse_VectorAnimationValue_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_VectorAnimationValue_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_VectorAnimationValue_mutable_vec_t;
typedef const struct Alloverse_RotationAnimationValue_table *Alloverse_RotationAnimationValue_table_t;
typedef struct Alloverse_RotationAnimationValue_table *Alloverse_RotationAnimationValue_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_RotationAnimationValue_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_RotationAnimationValue_mutable_vec_t;
typedef const struct Alloverse_TransformAnimationValue_table *Alloverse_TransformAnimationValue_table_t;
typedef struct Alloverse_TransformAnimationValue_table *Alloverse_TransformAnimationValue_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_TransformAnimationValue_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_TransformAnimationValue_mutable_vec_t;
typedef const struct Alloverse_PropertyAnimation_table *Alloverse_PropertyAnimation_table_t;
typedef struct Alloverse_PropertyAnimation_table *Alloverse_PropertyAnimation_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_PropertyAnimation_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_PropertyAnimation_mutable_vec_t;
typedef const struct Alloverse_PropertyAnimationsComponent_table *Alloverse_PropertyAnimationsComponent_table_t;
typedef struct Alloverse_PropertyAnimationsComponent_table *Alloverse_PropertyAnimationsComponent_mutable_table_t;
typedef const flatbuffers_uoffset_t *Alloverse_PropertyAnimationsComponent_vec_t;
typedef flatbuffers_uoffset_t *Alloverse_PropertyAnimationsComponent_mutable_vec_t;
#ifndef Alloverse_State_file_identifier
#define Alloverse_State_file_identifier 0
#endif
/* deprecated, use Alloverse_State_file_identifier */
#ifndef Alloverse_State_identifier
#define Alloverse_State_identifier 0
#endif
#define Alloverse_State_type_hash ((flatbuffers_thash_t)0x33abe795)
#define Alloverse_State_type_identifier "\x95\xe7\xab\x33"
#ifndef Alloverse_State_file_extension
#define Alloverse_State_file_extension "bin"
#endif
#ifndef Alloverse_Entity_file_identifier
#define Alloverse_Entity_file_identifier 0
#endif
/* deprecated, use Alloverse_Entity_file_identifier */
#ifndef Alloverse_Entity_identifier
#define Alloverse_Entity_identifier 0
#endif
#define Alloverse_Entity_type_hash ((flatbuffers_thash_t)0x35b7613b)
#define Alloverse_Entity_type_identifier "\x3b\x61\xb7\x35"
#ifndef Alloverse_Entity_file_extension
#define Alloverse_Entity_file_extension "bin"
#endif
#ifndef Alloverse_Components_file_identifier
#define Alloverse_Components_file_identifier 0
#endif
/* deprecated, use Alloverse_Components_file_identifier */
#ifndef Alloverse_Components_identifier
#define Alloverse_Components_identifier 0
#endif
#define Alloverse_Components_type_hash ((flatbuffers_thash_t)0x36db0934)
#define Alloverse_Components_type_identifier "\x34\x09\xdb\x36"
#ifndef Alloverse_Components_file_extension
#define Alloverse_Components_file_extension "bin"
#endif
#ifndef Alloverse_TransformComponent_file_identifier
#define Alloverse_TransformComponent_file_identifier 0
#endif
/* deprecated, use Alloverse_TransformComponent_file_identifier */
#ifndef Alloverse_TransformComponent_identifier
#define Alloverse_TransformComponent_identifier 0
#endif
#define Alloverse_TransformComponent_type_hash ((flatbuffers_thash_t)0x1b77ec2b)
#define Alloverse_TransformComponent_type_identifier "\x2b\xec\x77\x1b"
#ifndef Alloverse_TransformComponent_file_extension
#define Alloverse_TransformComponent_file_extension "bin"
#endif
#ifndef Alloverse_RelationshipsComponent_file_identifier
#define Alloverse_RelationshipsComponent_file_identifier 0
#endif
/* deprecated, use Alloverse_RelationshipsComponent_file_identifier */
#ifndef Alloverse_RelationshipsComponent_identifier
#define Alloverse_RelationshipsComponent_identifier 0
#endif
#define Alloverse_RelationshipsComponent_type_hash ((flatbuffers_thash_t)0x1c20c9a2)
#define Alloverse_RelationshipsComponent_type_identifier "\xa2\xc9\x20\x1c"
#ifndef Alloverse_RelationshipsComponent_file_extension
#define Alloverse_RelationshipsComponent_file_extension "bin"
#endif
#ifndef Alloverse_LiveMediaMetadata_file_identifier
#define Alloverse_LiveMediaMetadata_file_identifier 0
#endif
/* deprecated, use Alloverse_LiveMediaMetadata_file_identifier */
#ifndef Alloverse_LiveMediaMetadata_identifier
#define Alloverse_LiveMediaMetadata_identifier 0
#endif
#define Alloverse_LiveMediaMetadata_type_hash ((flatbuffers_thash_t)0xdd57d477)
#define Alloverse_LiveMediaMetadata_type_identifier "\x77\xd4\x57\xdd"
#ifndef Alloverse_LiveMediaMetadata_file_extension
#define Alloverse_LiveMediaMetadata_file_extension "bin"
#endif
#ifndef Alloverse_LiveMediaComponent_file_identifier
#define Alloverse_LiveMediaComponent_file_identifier 0
#endif
/* deprecated, use Alloverse_LiveMediaComponent_file_identifier */
#ifndef Alloverse_LiveMediaComponent_identifier
#define Alloverse_LiveMediaComponent_identifier 0
#endif
#define Alloverse_LiveMediaComponent_type_hash ((flatbuffers_thash_t)0xc8acee81)
#define Alloverse_LiveMediaComponent_type_identifier "\x81\xee\xac\xc8"
#ifndef Alloverse_LiveMediaComponent_file_extension
#define Alloverse_LiveMediaComponent_file_extension "bin"
#endif
#ifndef Alloverse_ClockComponent_file_identifier
#define Alloverse_ClockComponent_file_identifier 0
#endif
/* deprecated, use Alloverse_ClockComponent_file_identifier */
#ifndef Alloverse_ClockComponent_identifier
#define Alloverse_ClockComponent_identifier 0
#endif
#define Alloverse_ClockComponent_type_hash ((flatbuffers_thash_t)0xf35b3345)
#define Alloverse_ClockComponent_type_identifier "\x45\x33\x5b\xf3"
#ifndef Alloverse_ClockComponent_file_extension
#define Alloverse_ClockComponent_file_extension "bin"
#endif
#ifndef Alloverse_IntentComponent_file_identifier
#define Alloverse_IntentComponent_file_identifier 0
#endif
/* deprecated, use Alloverse_IntentComponent_file_identifier */
#ifndef Alloverse_IntentComponent_identifier
#define Alloverse_IntentComponent_identifier 0
#endif
#define Alloverse_IntentComponent_type_hash ((flatbuffers_thash_t)0xf0888b55)
#define Alloverse_IntentComponent_type_identifier "\x55\x8b\x88\xf0"
#ifndef Alloverse_IntentComponent_file_extension
#define Alloverse_IntentComponent_file_extension "bin"
#endif
#ifndef Alloverse_NumberAnimationValue_file_identifier
#define Alloverse_NumberAnimationValue_file_identifier 0
#endif
/* deprecated, use Alloverse_NumberAnimationValue_file_identifier */
#ifndef Alloverse_NumberAnimationValue_identifier
#define Alloverse_NumberAnimationValue_identifier 0
#endif
#define Alloverse_NumberAnimationValue_type_hash ((flatbuffers_thash_t)0x89ceeaa6)
#define Alloverse_NumberAnimationValue_type_identifier "\xa6\xea\xce\x89"
#ifndef Alloverse_NumberAnimationValue_file_extension
#define Alloverse_NumberAnimationValue_file_extension "bin"
#endif
#ifndef Alloverse_VectorAnimationValue_file_identifier
#define Alloverse_VectorAnimationValue_file_identifier 0
#endif
/* deprecated, use Alloverse_VectorAnimationValue_file_identifier */
#ifndef Alloverse_VectorAnimationValue_identifier
#define Alloverse_VectorAnimationValue_identifier 0
#endif
#define Alloverse_VectorAnimationValue_type_hash ((flatbuffers_thash_t)0x9fafb21c)
#define Alloverse_VectorAnimationValue_type_identifier "\x1c\xb2\xaf\x9f"
#ifndef Alloverse_VectorAnimationValue_file_extension
#define Alloverse_VectorAnimationValue_file_extension "bin"
#endif
#ifndef Alloverse_RotationAnimationValue_file_identifier
#define Alloverse_RotationAnimationValue_file_identifier 0
#endif
/* deprecated, use Alloverse_RotationAnimationValue_file_identifier */
#ifndef Alloverse_RotationAnimationValue_identifier
#define Alloverse_RotationAnimationValue_identifier 0
#endif
#define Alloverse_RotationAnimationValue_type_hash ((flatbuffers_thash_t)0xcb2b2c3d)
#define Alloverse_RotationAnimationValue_type_identifier "\x3d\x2c\x2b\xcb"
#ifndef Alloverse_RotationAnimationValue_file_extension
#define Alloverse_RotationAnimationValue_file_extension "bin"
#endif
#ifndef Alloverse_TransformAnimationValue_file_identifier
#define Alloverse_TransformAnimationValue_file_identifier 0
#endif
/* deprecated, use Alloverse_TransformAnimationValue_file_identifier */
#ifndef Alloverse_TransformAnimationValue_identifier
#define Alloverse_TransformAnimationValue_identifier 0
#endif
#define Alloverse_TransformAnimationValue_type_hash ((flatbuffers_thash_t)0xd2aa2c13)
#define Alloverse_TransformAnimationValue_type_identifier "\x13\x2c\xaa\xd2"
#ifndef Alloverse_TransformAnimationValue_file_extension
#define Alloverse_TransformAnimationValue_file_extension "bin"
#endif
#ifndef Alloverse_PropertyAnimation_file_identifier
#define Alloverse_PropertyAnimation_file_identifier 0
#endif
/* deprecated, use Alloverse_PropertyAnimation_file_identifier */
#ifndef Alloverse_PropertyAnimation_identifier
#define Alloverse_PropertyAnimation_identifier 0
#endif
#define Alloverse_PropertyAnimation_type_hash ((flatbuffers_thash_t)0x2abf6da1)
#define Alloverse_PropertyAnimation_type_identifier "\xa1\x6d\xbf\x2a"
#ifndef Alloverse_PropertyAnimation_file_extension
#define Alloverse_PropertyAnimation_file_extension "bin"
#endif
#ifndef Alloverse_PropertyAnimationsComponent_file_identifier
#define Alloverse_PropertyAnimationsComponent_file_identifier 0
#endif
/* deprecated, use Alloverse_PropertyAnimationsComponent_file_identifier */
#ifndef Alloverse_PropertyAnimationsComponent_identifier
#define Alloverse_PropertyAnimationsComponent_identifier 0
#endif
#define Alloverse_PropertyAnimationsComponent_type_hash ((flatbuffers_thash_t)0x85ac1165)
#define Alloverse_PropertyAnimationsComponent_type_identifier "\x65\x11\xac\x85"
#ifndef Alloverse_PropertyAnimationsComponent_file_extension
#define Alloverse_PropertyAnimationsComponent_file_extension "bin"
#endif
#ifndef Alloverse_Mat4_file_identifier
#define Alloverse_Mat4_file_identifier 0
#endif
/* deprecated, use Alloverse_Mat4_file_identifier */
#ifndef Alloverse_Mat4_identifier
#define Alloverse_Mat4_identifier 0
#endif
#define Alloverse_Mat4_type_hash ((flatbuffers_thash_t)0x5ea33d82)
#define Alloverse_Mat4_type_identifier "\x82\x3d\xa3\x5e"
#ifndef Alloverse_Mat4_file_extension
#define Alloverse_Mat4_file_extension "bin"
#endif
#ifndef Alloverse_Vec3_file_identifier
#define Alloverse_Vec3_file_identifier 0
#endif
/* deprecated, use Alloverse_Vec3_file_identifier */
#ifndef Alloverse_Vec3_identifier
#define Alloverse_Vec3_identifier 0
#endif
#define Alloverse_Vec3_type_hash ((flatbuffers_thash_t)0x7e71b453)
#define Alloverse_Vec3_type_identifier "\x53\xb4\x71\x7e"
#ifndef Alloverse_Vec3_file_extension
#define Alloverse_Vec3_file_extension "bin"
#endif


/** ////////////////////////////////////////////////////////////
 * ////////////////////////////////////////////////////////////  */
struct Alloverse_Mat4 {
    alignas(8) double m[16];
};
static_assert(sizeof(Alloverse_Mat4_t) == 128, "struct size mismatch");

static inline const Alloverse_Mat4_t *Alloverse_Mat4__const_ptr_add(const Alloverse_Mat4_t *p, size_t i) { return p + i; }
static inline Alloverse_Mat4_t *Alloverse_Mat4__ptr_add(Alloverse_Mat4_t *p, size_t i) { return p + i; }
static inline Alloverse_Mat4_struct_t Alloverse_Mat4_vec_at(Alloverse_Mat4_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t Alloverse_Mat4__size(void) { return 128; }
static inline size_t Alloverse_Mat4_vec_len(Alloverse_Mat4_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(Alloverse_Mat4)

__flatbuffers_define_struct_scalar_fixed_array_field(Alloverse_Mat4, m, flatbuffers_double, double, 16)

struct Alloverse_Vec3 {
    alignas(8) double v[3];
};
static_assert(sizeof(Alloverse_Vec3_t) == 24, "struct size mismatch");

static inline const Alloverse_Vec3_t *Alloverse_Vec3__const_ptr_add(const Alloverse_Vec3_t *p, size_t i) { return p + i; }
static inline Alloverse_Vec3_t *Alloverse_Vec3__ptr_add(Alloverse_Vec3_t *p, size_t i) { return p + i; }
static inline Alloverse_Vec3_struct_t Alloverse_Vec3_vec_at(Alloverse_Vec3_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t Alloverse_Vec3__size(void) { return 24; }
static inline size_t Alloverse_Vec3_vec_len(Alloverse_Vec3_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(Alloverse_Vec3)

__flatbuffers_define_struct_scalar_fixed_array_field(Alloverse_Vec3, v, flatbuffers_double, double, 3)


/** ////////////////////////////////////////////////////////////
 * //////////////////////////////////////////////////////////// */
struct Alloverse_State_table { uint8_t unused__; };

static inline size_t Alloverse_State_vec_len(Alloverse_State_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_State_table_t Alloverse_State_vec_at(Alloverse_State_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_State_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_State)

__flatbuffers_define_scalar_field(0, Alloverse_State, revision, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_vector_field(1, Alloverse_State, entities, Alloverse_Entity_vec_t, 0)

struct Alloverse_Entity_table { uint8_t unused__; };

static inline size_t Alloverse_Entity_vec_len(Alloverse_Entity_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_Entity_table_t Alloverse_Entity_vec_at(Alloverse_Entity_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_Entity_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_Entity)

__flatbuffers_define_string_field(0, Alloverse_Entity, id, 0)
__flatbuffers_define_find_by_string_field(Alloverse_Entity, id)
__flatbuffers_define_table_sort_by_string_field(Alloverse_Entity, id)
__flatbuffers_define_default_find_by_string_field(Alloverse_Entity, id)
__flatbuffers_define_default_scan_by_string_field(Alloverse_Entity, id)
#define Alloverse_Entity_vec_sort Alloverse_Entity_vec_sort_by_id
__flatbuffers_define_string_field(1, Alloverse_Entity, owner_agent_id, 0)
__flatbuffers_define_table_field(2, Alloverse_Entity, components, Alloverse_Components_table_t, 0)

struct Alloverse_Components_table { uint8_t unused__; };

static inline size_t Alloverse_Components_vec_len(Alloverse_Components_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_Components_table_t Alloverse_Components_vec_at(Alloverse_Components_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_Components_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_Components)

__flatbuffers_define_table_field(0, Alloverse_Components, transform, Alloverse_TransformComponent_table_t, 0)
__flatbuffers_define_table_field(1, Alloverse_Components, relationships, Alloverse_RelationshipsComponent_table_t, 0)
__flatbuffers_define_table_field(2, Alloverse_Components, live_media, Alloverse_LiveMediaComponent_table_t, 0)
__flatbuffers_define_table_field(3, Alloverse_Components, clock, Alloverse_ClockComponent_table_t, 0)
__flatbuffers_define_table_field(4, Alloverse_Components, intent, Alloverse_IntentComponent_table_t, 0)
__flatbuffers_define_table_field(5, Alloverse_Components, property_animations, Alloverse_PropertyAnimationsComponent_table_t, 0)
__flatbuffers_define_vector_field(6, Alloverse_Components, flex, flatbuffers_uint8_vec_t, 0)

/** ////////////////////////////////////////////////////////////
 * ////////////////////////////////////////////////////////////
 * ////////////////////////////////////////////////////////////
 * ////////////////////////////////////////////////////////////  */
struct Alloverse_TransformComponent_table { uint8_t unused__; };

static inline size_t Alloverse_TransformComponent_vec_len(Alloverse_TransformComponent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_TransformComponent_table_t Alloverse_TransformComponent_vec_at(Alloverse_TransformComponent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_TransformComponent_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_TransformComponent)

__flatbuffers_define_struct_field(0, Alloverse_TransformComponent, matrix, Alloverse_Mat4_struct_t, 0)

struct Alloverse_RelationshipsComponent_table { uint8_t unused__; };

static inline size_t Alloverse_RelationshipsComponent_vec_len(Alloverse_RelationshipsComponent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_RelationshipsComponent_table_t Alloverse_RelationshipsComponent_vec_at(Alloverse_RelationshipsComponent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_RelationshipsComponent_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_RelationshipsComponent)

__flatbuffers_define_string_field(0, Alloverse_RelationshipsComponent, parent, 0)

struct Alloverse_LiveMediaMetadata_table { uint8_t unused__; };

static inline size_t Alloverse_LiveMediaMetadata_vec_len(Alloverse_LiveMediaMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_LiveMediaMetadata_table_t Alloverse_LiveMediaMetadata_vec_at(Alloverse_LiveMediaMetadata_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_LiveMediaMetadata_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_LiveMediaMetadata)

__flatbuffers_define_scalar_field(0, Alloverse_LiveMediaMetadata, sample_rate, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(1, Alloverse_LiveMediaMetadata, channel_layout, 0)
__flatbuffers_define_scalar_field(2, Alloverse_LiveMediaMetadata, width, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(3, Alloverse_LiveMediaMetadata, height, flatbuffers_int32, int32_t, INT32_C(0))

struct Alloverse_LiveMediaComponent_table { uint8_t unused__; };

static inline size_t Alloverse_LiveMediaComponent_vec_len(Alloverse_LiveMediaComponent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_LiveMediaComponent_table_t Alloverse_LiveMediaComponent_vec_at(Alloverse_LiveMediaComponent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_LiveMediaComponent_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_LiveMediaComponent)

__flatbuffers_define_scalar_field(0, Alloverse_LiveMediaComponent, track_id, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(1, Alloverse_LiveMediaComponent, type, 0)
__flatbuffers_define_string_field(2, Alloverse_LiveMediaComponent, format, 0)
__flatbuffers_define_table_field(3, Alloverse_LiveMediaComponent, metadata, Alloverse_LiveMediaMetadata_table_t, 0)

struct Alloverse_ClockComponent_table { uint8_t unused__; };

static inline size_t Alloverse_ClockComponent_vec_len(Alloverse_ClockComponent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_ClockComponent_table_t Alloverse_ClockComponent_vec_at(Alloverse_ClockComponent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_ClockComponent_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_ClockComponent)

__flatbuffers_define_scalar_field(0, Alloverse_ClockComponent, time, flatbuffers_double, double, 0.0000000000000000)

struct Alloverse_IntentComponent_table { uint8_t unused__; };

static inline size_t Alloverse_IntentComponent_vec_len(Alloverse_IntentComponent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_IntentComponent_table_t Alloverse_IntentComponent_vec_at(Alloverse_IntentComponent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_IntentComponent_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_IntentComponent)

__flatbuffers_define_string_field(0, Alloverse_IntentComponent, actuate_pose, 0)
__flatbuffers_define_string_field(1, Alloverse_IntentComponent, from_avatar, 0)

struct Alloverse_NumberAnimationValue_table { uint8_t unused__; };

static inline size_t Alloverse_NumberAnimationValue_vec_len(Alloverse_NumberAnimationValue_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_NumberAnimationValue_table_t Alloverse_NumberAnimationValue_vec_at(Alloverse_NumberAnimationValue_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_NumberAnimationValue_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_NumberAnimationValue)

__flatbuffers_define_scalar_field(0, Alloverse_NumberAnimationValue, number, flatbuffers_double, double, 0.0000000000000000)

struct Alloverse_VectorAnimationValue_table { uint8_t unused__; };

static inline size_t Alloverse_VectorAnimationValue_vec_len(Alloverse_VectorAnimationValue_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_VectorAnimationValue_table_t Alloverse_VectorAnimationValue_vec_at(Alloverse_VectorAnimationValue_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_VectorAnimationValue_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_VectorAnimationValue)

__flatbuffers_define_struct_field(0, Alloverse_VectorAnimationValue, vector, Alloverse_Vec3_struct_t, 0)

struct Alloverse_RotationAnimationValue_table { uint8_t unused__; };

static inline size_t Alloverse_RotationAnimationValue_vec_len(Alloverse_RotationAnimationValue_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_RotationAnimationValue_table_t Alloverse_RotationAnimationValue_vec_at(Alloverse_RotationAnimationValue_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_RotationAnimationValue_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_RotationAnimationValue)

__flatbuffers_define_scalar_field(0, Alloverse_RotationAnimationValue, angle, flatbuffers_double, double, 0.0000000000000000)
__flatbuffers_define_struct_field(1, Alloverse_RotationAnimationValue, axis, Alloverse_Vec3_struct_t, 0)

struct Alloverse_TransformAnimationValue_table { uint8_t unused__; };

static inline size_t Alloverse_TransformAnimationValue_vec_len(Alloverse_TransformAnimationValue_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_TransformAnimationValue_table_t Alloverse_TransformAnimationValue_vec_at(Alloverse_TransformAnimationValue_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_TransformAnimationValue_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_TransformAnimationValue)

__flatbuffers_define_struct_field(0, Alloverse_TransformAnimationValue, matrix, Alloverse_Mat4_struct_t, 0)
typedef uint8_t Alloverse_AnimationValue_union_type_t;
__flatbuffers_define_integer_type(Alloverse_AnimationValue, Alloverse_AnimationValue_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, Alloverse_AnimationValue)
#define Alloverse_AnimationValue_NONE ((Alloverse_AnimationValue_union_type_t)UINT8_C(0))
#define Alloverse_AnimationValue_number ((Alloverse_AnimationValue_union_type_t)UINT8_C(1))
#define Alloverse_AnimationValue_vector ((Alloverse_AnimationValue_union_type_t)UINT8_C(2))
#define Alloverse_AnimationValue_rotation ((Alloverse_AnimationValue_union_type_t)UINT8_C(3))
#define Alloverse_AnimationValue_matrix ((Alloverse_AnimationValue_union_type_t)UINT8_C(4))

static inline const char *Alloverse_AnimationValue_type_name(Alloverse_AnimationValue_union_type_t type)
{
    switch (type) {
    case Alloverse_AnimationValue_NONE: return "NONE";
    case Alloverse_AnimationValue_number: return "number";
    case Alloverse_AnimationValue_vector: return "vector";
    case Alloverse_AnimationValue_rotation: return "rotation";
    case Alloverse_AnimationValue_matrix: return "matrix";
    default: return "";
    }
}

static inline int Alloverse_AnimationValue_is_known_type(Alloverse_AnimationValue_union_type_t type)
{
    switch (type) {
    case Alloverse_AnimationValue_NONE: return 1;
    case Alloverse_AnimationValue_number: return 1;
    case Alloverse_AnimationValue_vector: return 1;
    case Alloverse_AnimationValue_rotation: return 1;
    case Alloverse_AnimationValue_matrix: return 1;
    default: return 0;
    }
}


struct Alloverse_PropertyAnimation_table { uint8_t unused__; };

static inline size_t Alloverse_PropertyAnimation_vec_len(Alloverse_PropertyAnimation_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_PropertyAnimation_table_t Alloverse_PropertyAnimation_vec_at(Alloverse_PropertyAnimation_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_PropertyAnimation_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_PropertyAnimation)

__flatbuffers_define_string_field(0, Alloverse_PropertyAnimation, id, 0)
__flatbuffers_define_find_by_string_field(Alloverse_PropertyAnimation, id)
__flatbuffers_define_table_sort_by_string_field(Alloverse_PropertyAnimation, id)
__flatbuffers_define_default_find_by_string_field(Alloverse_PropertyAnimation, id)
__flatbuffers_define_default_scan_by_string_field(Alloverse_PropertyAnimation, id)
#define Alloverse_PropertyAnimation_vec_sort Alloverse_PropertyAnimation_vec_sort_by_id
__flatbuffers_define_string_field(1, Alloverse_PropertyAnimation, path, 0)
__flatbuffers_define_union_field(flatbuffers_, 3, Alloverse_PropertyAnimation, from, Alloverse_AnimationValue, 0)
__flatbuffers_define_union_field(flatbuffers_, 5, Alloverse_PropertyAnimation, to, Alloverse_AnimationValue, 0)
__flatbuffers_define_scalar_field(6, Alloverse_PropertyAnimation, start_at, flatbuffers_double, double, 0.0000000000000000)
__flatbuffers_define_scalar_field(7, Alloverse_PropertyAnimation, duration, flatbuffers_double, double, 1.0000000000000000)
__flatbuffers_define_string_field(8, Alloverse_PropertyAnimation, easing, 0)
__flatbuffers_define_scalar_field(9, Alloverse_PropertyAnimation, repeats, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(10, Alloverse_PropertyAnimation, autoreverses, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))

struct Alloverse_PropertyAnimationsComponent_table { uint8_t unused__; };

static inline size_t Alloverse_PropertyAnimationsComponent_vec_len(Alloverse_PropertyAnimationsComponent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Alloverse_PropertyAnimationsComponent_table_t Alloverse_PropertyAnimationsComponent_vec_at(Alloverse_PropertyAnimationsComponent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Alloverse_PropertyAnimationsComponent_table_t, vec, i, 0)
__flatbuffers_table_as_root(Alloverse_PropertyAnimationsComponent)

__flatbuffers_define_vector_field(0, Alloverse_PropertyAnimationsComponent, animations, Alloverse_PropertyAnimation_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* ALLOVERSE_READER_H */
